# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccfde229e5d1c13a3706e276a7745021b048ec4dd15311fa4b8082425652c0246b371e3107d657607c88aa9657b1cb5a0c15258b637983ba8a645f30eb0d385f

test:
  secret_key_base: 666f5b2ecc0b55c171546aa18dada5dbcb39bc06e147ccb555b3fb55849e4186b85371af1746e9d3e9231fac1744794604f040b16c5d8d9a50233724f2d8ab8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
